# Generated by Django 5.2.7 on 2025-10-27 04:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                ("original_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=100)),
                ("file_size", models.IntegerField()),
                (
                    "upload_type",
                    models.CharField(
                        choices=[
                            ("avatar", "Avatar"),
                            ("cover", "Cover Photo"),
                            ("post", "Post Attachment"),
                            ("resource", "Resource File"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_processed", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
