# Generated by Django 5.2.7 on 2025-10-26 03:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("post_like", "Like sur post"),
                            ("post_comment", "Commentaire sur post"),
                            ("comment_reply", "Réponse à commentaire"),
                            ("sphere_invitation", "Invitation à une sphère"),
                            ("sphere_join_request", "Demande d'adhésion"),
                            ("task_assigned", "Tâche assignée"),
                            ("task_completed", "Tâche terminée"),
                            ("resource_shared", "Ressource partagée"),
                            ("connection_request", "Demande de connexion"),
                            ("connection_accepted", "Connexion acceptée"),
                            ("message_received", "Message reçu"),
                            ("system", "Notification système"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_post_likes", models.BooleanField(default=True)),
                ("email_post_comments", models.BooleanField(default=True)),
                ("email_sphere_invitations", models.BooleanField(default=True)),
                ("email_task_assignments", models.BooleanField(default=True)),
                ("email_messages", models.BooleanField(default=True)),
                ("push_post_likes", models.BooleanField(default=False)),
                ("push_post_comments", models.BooleanField(default=True)),
                ("push_sphere_invitations", models.BooleanField(default=True)),
                ("push_task_assignments", models.BooleanField(default=True)),
                ("push_messages", models.BooleanField(default=True)),
                ("in_app_post_likes", models.BooleanField(default=True)),
                ("in_app_post_comments", models.BooleanField(default=True)),
                ("in_app_sphere_invitations", models.BooleanField(default=True)),
                ("in_app_task_assignments", models.BooleanField(default=True)),
                ("in_app_messages", models.BooleanField(default=True)),
                ("system_updates", models.BooleanField(default=True)),
                ("marketing_emails", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Notification Settings",
                "verbose_name_plural": "Notification Settings",
            },
        ),
    ]
