# Generated by Django 5.2.7 on 2026-04-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('post_like', 'Like sur post'), ('post_comment', 'Commentaire sur post'), ('mention_post', 'Mention dans un post'), ('mention_comment', 'Mention dans un commentaire'), ('comment_reply', 'Réponse à commentaire'), ('sphere_invitation', 'Invitation à une sphère'), ('sphere_join_request', "Demande d'adhésion"), ('task_assigned', 'Tâche assignée'), ('task_completed', 'Tâche terminée'), ('resource_shared', 'Ressource partagée'), ('connection_request', 'Demande de connexion'), ('connection_accepted', 'Connexion acceptée'), ('message', 'Message reçu'), ('system', 'Notification système')], max_length=30),
        ),
    ]
