# Generated by Django 5.2.7 on 2026-05-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_add_resource_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='subject',
            field=models.CharField(blank=True, default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('cours', 'Cours'), ('notes', 'Notes'), ('resumes', 'Résumés'), ('exercises', 'Exercices'), ('projects', 'Projets'), ('presentations', 'Présentations'), ('exam_papers', 'Anciens Sujets'), ('other', 'Autre')], max_length=20),
        ),
    ]
