# Generated by Django 5.2.7 on 2026-05-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_resource_file_type_alter_resource_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('cours', 'Cours'), ('notes', 'Notes'), ('resumes', 'Résumés'), ('exercises', 'Exercices'), ('projects', 'Projets'), ('presentations', 'Présentations'), ('exam_papers', "Épreuves d'examen"), ('other', 'Autre')], max_length=20),
        ),
    ]
