# Generated by Django 5.2.7 on 2025-10-26 03:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sphere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "Académique"),
                            ("professional", "Professionnel"),
                            ("social", "Social"),
                            ("sports", "Sports"),
                            ("arts", "Arts"),
                            ("technology", "Technologie"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("study", "Étude"),
                            ("project", "Projet"),
                            ("club", "Club"),
                            ("event", "Événement"),
                            ("networking", "Réseautage"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("color", models.CharField(default="#10b981", max_length=20)),
                ("icon", models.CharField(default="users", max_length=50)),
                ("is_private", models.BooleanField(default=False)),
                ("require_approval", models.BooleanField(default=False)),
                ("objective", models.TextField(blank=True)),
                ("target_audience", models.CharField(blank=True, max_length=200)),
                ("duration", models.CharField(default="permanent", max_length=50)),
                ("collaboration_types", models.JSONField(blank=True, default=list)),
                ("member_count", models.IntegerField(default=0)),
                ("impact_score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SphereMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrateur"),
                            ("moderator", "Modérateur"),
                            ("member", "Membre"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("pending", "En attente"),
                            ("inactive", "Inactif"),
                            ("banned", "Banni"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-joined_at"],
            },
        ),
    ]
