# Generated by Django 5.2.7 on 2026-05-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spheres', '0004_spherefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sphere',
            name='type',
        ),
        migrations.AddField(
            model_name='sphere',
            name='sphere_type',
            field=models.CharField(choices=[('cours', 'Sphère de Cours'), ('projet', 'Sphère de Projet'), ('club', 'Club / Association'), ('revision', 'Sphère de Révision'), ('communaute', 'Communauté')], default='communaute', max_length=20),
        ),
    ]
