"""
Django settings for campus_sphere project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import logging
import os
from pathlib import Path
from decouple import config as env_config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = env_config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1',
    cast=Csv(),
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party apps
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "channels",
    "django_filters",

    # Local apps
    "users",
    "spheres",
    "posts",
    "resources",
    "tasks",
    "messaging",
    "notifications",
    "sphera",

    # Security apps
    "upload",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # Security middleware
]

ROOT_URLCONF = "campus_sphere.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "campus_sphere.wsgi.application"

# ASGI Application for WebSockets (used by Daphne / Channels)
ASGI_APPLICATION = "campus_sphere.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Supabase PostgreSQL Configuration
# ⚠️ IMPORTANT: Ne mettez JAMAIS de valeurs par défaut sensibles ici !
# Utilisez un fichier .env pour stocker vos credentials

# Support pour DATABASE_URL (recommandé) ou paramètres individuels
DATABASE_URL = env_config('DATABASE_URL', default=None)

if DATABASE_URL:
    import dj_database_url
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=0, # Préférable pour Supabase (évite de saturer les connexions)
            ssl_require=True
        )
    }
else:
    # Vérifier si les paramètres PostgreSQL sont fournis
    DB_NAME = env_config('DB_NAME', default=None)
    DB_USER = env_config('DB_USER', default=None)
    DB_PASSWORD = env_config('DB_PASSWORD', default=None)
    DB_HOST = env_config('DB_HOST', default=None)
    
    # Si les paramètres PostgreSQL sont fournis, utiliser PostgreSQL
    if DB_NAME and DB_USER and DB_PASSWORD and DB_HOST:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": DB_NAME,
                "USER": DB_USER,
                "PASSWORD": DB_PASSWORD,
                "HOST": DB_HOST,
                "PORT": env_config('DB_PORT', default='5432'),
                "OPTIONS": {
                    "sslmode": env_config('DB_SSLMODE', default='require'),
                },
                "CONN_MAX_AGE": 600,  # Connection pooling
            }
        }
    else:
        # Fallback vers SQLite pour le développement
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

#
# Redis / Cache / Channels / Celery (enabled when REDIS_URL is provided)
#
REDIS_URL = env_config('REDIS_URL', default=None)
settings_logger = logging.getLogger("campus_sphere.settings")

if REDIS_URL:
    # Handle SSL for rediss://
    redis_options = {
        "CLIENT_CLASS": "django_redis.client.DefaultClient",
        "SOCKET_CONNECT_TIMEOUT": 5,
        "SOCKET_TIMEOUT": 5,
        "IGNORE_EXCEPTIONS": True,
    }
    
    # If using rediss://, we need to handle SSL requirements
    if REDIS_URL.startswith('rediss://'):
        redis_options["CONNECTION_POOL_KWARGS"] = {"ssl_cert_reqs": None}

    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": redis_options,
            "KEY_PREFIX": env_config("CACHE_KEY_PREFIX", default="campussphere"),
            "TIMEOUT": 86400,
        },
    }
    
    # WebSocket Channel Layer
    channel_hosts = [REDIS_URL]
    if REDIS_URL.startswith('rediss://'):
        # For channels_redis, we use a dict for host to pass SSL options
        channel_hosts = [{
            "address": REDIS_URL,
            "ssl_cert_reqs": None,
        }]

    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": channel_hosts,
                "symmetric_encryption_keys": [SECRET_KEY],
                "capacity": 1000,
                "expiry": 20,
            },
        },
    }

    # Celery Configuration
    CELERY_BROKER_URL = REDIS_URL
    CELERY_RESULT_BACKEND = REDIS_URL
    CELERY_ACCEPT_CONTENT = ['json']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_RESULT_SERIALIZER = 'json'
    CELERY_TIMEZONE = TIME_ZONE

    CELERY_BEAT_SCHEDULE = {
        'cleanup-expired-spheres-hourly': {
            'task': 'spheres.tasks.cleanup_expired_spheres_task',
            'schedule': 3600.0,
        },
    }
    
    # Log ignored Redis errors as warnings instead of crashing requests.
    DJANGO_REDIS_LOG_IGNORED_EXCEPTIONS = True
    DJANGO_REDIS_LOGGER = "campus_sphere.settings"
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "campus-sphere-local-cache",
            "TIMEOUT": 86400,
        },
    }
    settings_logger.warning(
        "REDIS_URL is not set; using LocMemCache as fallback for cache and sessions."
    )

# Sessions stockées en base (survivent aux redémarrages) + cache (vitesse)
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
SESSION_CACHE_ALIAS = "default"
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14  # 14 jours
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "None"

# CORS / CSRF Configuration
CORS_ALLOWED_ORIGINS = env_config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:5173,http://localhost:3000,https://www.campussphere.app,https://campussphere.app,https://api.campussphere.app",
    cast=Csv(),
)

CSRF_TRUSTED_ORIGINS = env_config(
    "CSRF_TRUSTED_ORIGINS",
    default="http://localhost:5173,http://localhost:3000,https://www.campussphere.app,https://campussphere.app,https://api.campussphere.app",
    cast=Csv(),
)

CORS_ALLOW_CREDENTIALS = True
FRONTEND_URL = env_config("FRONTEND_URL", default="http://localhost:8080")

# Supabase Auth
SUPABASE_URL = env_config("SUPABASE_URL", default="")
SUPABASE_JWT_SECRET = env_config("SUPABASE_JWT_SECRET", default="")
SUPABASE_SERVICE_ROLE_KEY = env_config("SUPABASE_SERVICE_ROLE_KEY", default="")

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/hour',           # Taux général anonyme
        'guest_generate': '5/hour',  # Endpoint Sphera guest (5 générations/heure/IP)
    },
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=90),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# File Storage Configuration (Local or S3)
USE_S3 = env_config("USE_S3", default=False, cast=bool)

if USE_S3:
    AWS_ACCESS_KEY_ID = env_config("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = env_config("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = env_config("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = env_config("AWS_S3_REGION_NAME", default="eu-west-1")
    AWS_S3_SIGNATURE_VERSION = env_config("AWS_S3_SIGNATURE_VERSION", default="s3v4")
    AWS_S3_FILE_OVERWRITE = env_config("AWS_S3_FILE_OVERWRITE", default=False, cast=bool)
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = env_config("AWS_QUERYSTRING_AUTH", default=False, cast=bool)

    AWS_S3_CUSTOM_DOMAIN = env_config("AWS_S3_CUSTOM_DOMAIN", default="")
    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"
    else:
        MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/media/"

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "location": "media",
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Production settings for Vercel + Render
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # 1 year in production only
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG

# Security Middleware
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = not DEBUG

# Rate Limiting
# RATELIMIT_VIEW = 'campus_sphere.views.ratelimit_error'  # Commented out - ratelimit not installed

# Axes (Brute Force Protection)
# AXES_FAILURE_LIMIT = 5  # Commented out - axes not installed
# AXES_COOLOFF_TIME = 1  # hours
# AXES_RESET_ON_SUCCESS = True
# AXES_LOCKOUT_URL = '/locked/'
# AXES_LOCKOUT_TEMPLATE = 'axes/lockout.html'

# Production Settings
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = 'Lax'

# File Upload Security
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB
FILE_UPLOAD_PERMISSIONS = 0o644

# Connections visibility policy
# - own_only: only users can list their own full connections
# - public_profile: authenticated users can list connections from another profile
# Production default is public_profile (can still be overridden with env var)
CONNECTION_LIST_VISIBILITY_POLICY = os.getenv(
    'CONNECTION_LIST_VISIBILITY_POLICY',
    'public_profile' if not DEBUG else 'own_only'
)

# Content Security Policy (can be added later with django-csp)

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env_config('EMAIL_HOST_USER', default='your-email@gmail.com')
EMAIL_HOST_PASSWORD = env_config('EMAIL_HOST_PASSWORD', default='your-app-password')
DEFAULT_FROM_EMAIL = 'CampusSphere <no-reply@campussphere.app>'

# Celery Configuration for Background Tasks
# Redis Configuration for Channels and Celery
# Static Files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise optimization for memory
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_USE_FINDERS = True
WHITENOISE_MAX_AGE = 31536000  # 1 year

# AI API Keys
ANTHROPIC_API_KEY = env_config('ANTHROPIC_API_KEY', default=None)
GEMINI_API_KEY = env_config('GEMINI_API_KEY', default=None)
GROQ_API_KEY = env_config('GROQ_API_KEY', default=None)

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'campus_sphere': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'sphera': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'asgiref.sync': {
            'handlers': ['console'],
            'level': 'CRITICAL',
            'propagate': False,
        },
    },
}
