// GENERATED from documentation/API_INVENTORY.md — do not edit by hand.
// Regenerate with: python3 backend/scripts/gen-route-manifest.py

export type RouteStatus = "ACTIVE" | "UNUSED" | "DEPRECATED" | "INFRA";

export interface RouteSpec {
  /** Path template; `<var>` marks a path parameter. */
  path: string;
  methods: string[];
  status: RouteStatus;
  /** True when the route must be reachable without an Authorization header. */
  public: boolean;
  /** True when the route requires platform-admin privileges. */
  admin: boolean;
}

export const ROUTES: RouteSpec[] = [
  { path: "api/admin/moderation-queue/", methods: ["GET"], status: "ACTIVE", public: false, admin: true },
  { path: "api/admin/permissions/", methods: ["GET"], status: "ACTIVE", public: false, admin: true },
  { path: "api/admin/reported-content/", methods: ["GET"], status: "ACTIVE", public: false, admin: true },
  { path: "api/admin/user-management-summary/", methods: ["GET"], status: "ACTIVE", public: false, admin: true },
  { path: "api/admin/v1/logs/", methods: ["GET"], status: "ACTIVE", public: false, admin: true },
  { path: "api/admin/v1/posts/", methods: ["GET"], status: "UNUSED", public: false, admin: true },
  { path: "api/admin/v1/posts/bulk-delete/", methods: ["POST"], status: "UNUSED", public: false, admin: true },
  { path: "api/admin/v1/reports/", methods: ["GET"], status: "ACTIVE", public: false, admin: true },
  { path: "api/admin/v1/reports/bulk-approve/", methods: ["POST"], status: "ACTIVE", public: false, admin: true },
  { path: "api/admin/v1/resources/", methods: ["GET"], status: "ACTIVE", public: false, admin: true },
  { path: "api/admin/v1/resources/bulk-delete/", methods: ["POST"], status: "ACTIVE", public: false, admin: true },
  { path: "api/admin/v1/spheres/", methods: ["GET"], status: "ACTIVE", public: false, admin: true },
  { path: "api/admin/v1/stats/", methods: ["GET"], status: "ACTIVE", public: false, admin: true },
  { path: "api/admin/v1/users/", methods: ["GET"], status: "ACTIVE", public: false, admin: true },
  { path: "api/admin/v1/users/bulk-ban/", methods: ["POST"], status: "ACTIVE", public: false, admin: true },
  { path: "api/admin/v1/users/verify/", methods: ["POST"], status: "ACTIVE", public: false, admin: true },
  { path: "api/admin/v1/verification-queue/", methods: ["GET"], status: "ACTIVE", public: false, admin: true },
  { path: "api/auth/refresh/", methods: ["POST"], status: "ACTIVE", public: true, admin: false },
  { path: "api/auth/supabase/complete-profile/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/auth/supabase/debug/", methods: ["GET"], status: "DEPRECATED", public: false, admin: false },
  { path: "api/auth/supabase/exchange/", methods: ["POST"], status: "ACTIVE", public: true, admin: false },
  { path: "api/conversations/", methods: ["GET", "POST"], status: "UNUSED", public: false, admin: false },
  { path: "api/conversations/<var>/", methods: ["GET", "PUT", "PATCH", "DELETE"], status: "ACTIVE", public: false, admin: false },
  { path: "api/conversations/<var>/avatar/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/conversations/<var>/leave/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/conversations/<var>/messages/", methods: ["GET", "POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/conversations/<var>/messages/<var>/", methods: ["GET", "PATCH", "DELETE"], status: "ACTIVE", public: false, admin: false },
  { path: "api/conversations/<var>/participants/", methods: ["GET"], status: "ACTIVE", public: false, admin: false },
  { path: "api/conversations/<var>/participants/<var>/remove/", methods: ["DELETE"], status: "ACTIVE", public: false, admin: false },
  { path: "api/conversations/<var>/participants/add/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/conversations/<var>/read/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/conversations/<var>/unread/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/conversations/group/create/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/conversations/private/create/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/conversations/user/", methods: ["GET"], status: "ACTIVE", public: false, admin: false },
  { path: "api/filters/", methods: ["GET"], status: "UNUSED", public: false, admin: false },
  { path: "api/health/", methods: ["GET"], status: "INFRA", public: true, admin: false },
  { path: "api/info/", methods: ["GET"], status: "DEPRECATED", public: true, admin: false },
  { path: "api/notifications/", methods: ["GET"], status: "ACTIVE", public: false, admin: false },
  { path: "api/notifications/<var>/", methods: ["GET", "PUT", "PATCH", "DELETE"], status: "ACTIVE", public: false, admin: false },
  { path: "api/notifications/<var>/read/", methods: ["PUT"], status: "ACTIVE", public: false, admin: false },
  { path: "api/notifications/read-all/", methods: ["PUT"], status: "ACTIVE", public: false, admin: false },
  { path: "api/notifications/settings/", methods: ["PUT", "PATCH"], status: "ACTIVE", public: false, admin: false },
  { path: "api/notifications/stats/", methods: ["GET"], status: "UNUSED", public: false, admin: false },
  { path: "api/posts/", methods: ["GET", "POST"], status: "ACTIVE", public: true, admin: false },
  { path: "api/posts/<var>/", methods: ["GET", "PUT", "PATCH", "DELETE"], status: "ACTIVE", public: true, admin: false },
  { path: "api/posts/<var>/comments/", methods: ["GET", "POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/posts/<var>/impact-rate/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/posts/<var>/like/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/posts/<var>/pin/", methods: ["POST"], status: "UNUSED", public: false, admin: false },
  { path: "api/posts/<var>/report/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/posts/<var>/save/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/posts/comments/<var>/", methods: ["GET", "PUT", "PATCH", "DELETE"], status: "ACTIVE", public: false, admin: false },
  { path: "api/posts/comments/<var>/like/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/posts/saved/", methods: ["GET"], status: "ACTIVE", public: false, admin: false },
  { path: "api/posts/sphere/<var>/", methods: ["GET"], status: "UNUSED", public: false, admin: false },
  { path: "api/posts/user/<var>/", methods: ["GET"], status: "ACTIVE", public: false, admin: false },
  { path: "api/resources/", methods: ["GET", "POST"], status: "ACTIVE", public: true, admin: false },
  { path: "api/resources/<var>/", methods: ["GET", "PUT", "PATCH", "DELETE"], status: "ACTIVE", public: true, admin: false },
  { path: "api/resources/<var>/download/", methods: ["POST"], status: "ACTIVE", public: true, admin: false },
  { path: "api/resources/<var>/preview/", methods: ["GET"], status: "ACTIVE", public: true, admin: false },
  { path: "api/resources/<var>/report/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/resources/<var>/save/", methods: ["POST", "DELETE"], status: "ACTIVE", public: false, admin: false },
  { path: "api/resources/<var>/share/", methods: ["POST"], status: "ACTIVE", public: true, admin: false },
  { path: "api/resources/<var>/view/", methods: ["POST"], status: "UNUSED", public: false, admin: false },
  { path: "api/resources/folders/", methods: ["GET", "POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/resources/folders/<var>/", methods: ["GET", "PUT", "PATCH", "DELETE"], status: "ACTIVE", public: false, admin: false },
  { path: "api/resources/folders/<var>/download/", methods: ["GET"], status: "ACTIVE", public: false, admin: false },
  { path: "api/resources/saved/", methods: ["GET"], status: "ACTIVE", public: false, admin: false },
  { path: "api/resources/sphere/<var>/", methods: ["GET"], status: "UNUSED", public: false, admin: false },
  { path: "api/resources/user/<var>/", methods: ["GET"], status: "ACTIVE", public: false, admin: false },
  { path: "api/search/", methods: ["GET"], status: "ACTIVE", public: false, admin: false },
  { path: "api/search/suggestions/", methods: ["GET"], status: "UNUSED", public: false, admin: false },
  { path: "api/sphera/annales/", methods: ["GET"], status: "ACTIVE", public: false, admin: false },
  { path: "api/sphera/annales/<var>/", methods: ["GET", "DELETE"], status: "ACTIVE", public: false, admin: false },
  { path: "api/sphera/annales/<var>/ask/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/sphera/annales/<var>/share/", methods: ["POST", "DELETE"], status: "ACTIVE", public: false, admin: false },
  { path: "api/sphera/generate/annale/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/sphera/generate/from-resource/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/sphera/generate/from-upload/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/sphera/guest/generate/", methods: ["POST"], status: "ACTIVE", public: true, admin: false },
  { path: "api/sphera/sessions/", methods: ["GET"], status: "ACTIVE", public: false, admin: false },
  { path: "api/sphera/sessions/<var>/", methods: ["GET", "DELETE"], status: "ACTIVE", public: false, admin: false },
  { path: "api/sphera/sessions/<var>/add-tool/", methods: ["PATCH"], status: "ACTIVE", public: false, admin: false },
  { path: "api/sphera/sessions/<var>/ask/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/sphera/sessions/<var>/share/", methods: ["POST", "DELETE"], status: "ACTIVE", public: false, admin: false },
  { path: "api/sphera/sessions/<var>/suggestions/", methods: ["GET"], status: "ACTIVE", public: false, admin: false },
  { path: "api/sphera/sphere/<var>/", methods: ["GET"], status: "ACTIVE", public: false, admin: false },
  { path: "api/sphera/sphere/<var>/annales/", methods: ["GET"], status: "ACTIVE", public: false, admin: false },
  { path: "api/spheres/", methods: ["GET", "POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/spheres/<var>/", methods: ["GET", "PUT", "PATCH", "DELETE"], status: "ACTIVE", public: false, admin: false },
  { path: "api/spheres/<var>/banner/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/spheres/<var>/cancel-request/", methods: ["DELETE"], status: "ACTIVE", public: false, admin: false },
  { path: "api/spheres/<var>/extend-duration/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/spheres/<var>/features/", methods: ["GET"], status: "UNUSED", public: false, admin: false },
  { path: "api/spheres/<var>/files/", methods: ["GET", "POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/spheres/<var>/files/<var>/", methods: ["DELETE"], status: "ACTIVE", public: false, admin: false },
  { path: "api/spheres/<var>/join/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/spheres/<var>/leave/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/spheres/<var>/members/", methods: ["GET", "POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/spheres/<var>/members/<var>/", methods: ["PATCH", "DELETE"], status: "ACTIVE", public: false, admin: false },
  { path: "api/spheres/<var>/overview/", methods: ["GET"], status: "ACTIVE", public: false, admin: false },
  { path: "api/spheres/user/spheres/", methods: ["GET"], status: "ACTIVE", public: false, admin: false },
  { path: "api/tasks/", methods: ["GET", "POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/tasks/<var>/", methods: ["GET", "PUT", "PATCH", "DELETE"], status: "ACTIVE", public: false, admin: false },
  { path: "api/tasks/<var>/assign/", methods: ["POST"], status: "UNUSED", public: false, admin: false },
  { path: "api/tasks/<var>/complete/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/tasks/<var>/move/", methods: ["PATCH"], status: "ACTIVE", public: false, admin: false },
  { path: "api/tasks/sphere/<var>/", methods: ["GET"], status: "ACTIVE", public: false, admin: false },
  { path: "api/tasks/user/", methods: ["GET"], status: "UNUSED", public: false, admin: false },
  { path: "api/tasks/user/<var>/", methods: ["GET"], status: "UNUSED", public: false, admin: false },
  { path: "api/upload/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/upload/<var>/", methods: ["DELETE"], status: "UNUSED", public: false, admin: false },
  { path: "api/uploads/", methods: ["GET"], status: "UNUSED", public: false, admin: false },
  { path: "api/uploads/stats/", methods: ["GET"], status: "UNUSED", public: false, admin: false },
  { path: "api/users/<var>/", methods: ["GET"], status: "ACTIVE", public: true, admin: false },
  { path: "api/users/<var>/avatar/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/users/<var>/connection-relation/", methods: ["GET", "POST", "PATCH", "DELETE"], status: "ACTIVE", public: false, admin: false },
  { path: "api/users/<var>/connections/", methods: ["GET", "POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/users/<var>/connections/<var>/", methods: ["DELETE"], status: "ACTIVE", public: false, admin: false },
  { path: "api/users/<var>/cover/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/users/admin/contact-messages/", methods: ["GET"], status: "ACTIVE", public: false, admin: true },
  { path: "api/users/admin/contact-messages/<var>/", methods: ["GET", "PUT", "PATCH", "DELETE"], status: "ACTIVE", public: false, admin: true },
  { path: "api/users/auth/change-email/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/users/auth/change-password/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/users/auth/delete-account/", methods: ["DELETE"], status: "ACTIVE", public: false, admin: false },
  { path: "api/users/auth/login/", methods: ["POST"], status: "ACTIVE", public: true, admin: false },
  { path: "api/users/auth/logout/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/users/auth/me/", methods: ["GET"], status: "ACTIVE", public: true, admin: false },
  { path: "api/users/auth/password-reset/", methods: ["POST"], status: "DEPRECATED", public: true, admin: false },
  { path: "api/users/auth/register/", methods: ["POST"], status: "ACTIVE", public: true, admin: false },
  { path: "api/users/auth/supabase/complete-profile/", methods: ["POST"], status: "DEPRECATED", public: false, admin: false },
  { path: "api/users/auth/supabase/exchange-token/", methods: ["POST"], status: "DEPRECATED", public: true, admin: false },
  { path: "api/users/blocks/", methods: ["GET", "POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/users/blocks/<var>/", methods: ["DELETE"], status: "ACTIVE", public: false, admin: false },
  { path: "api/users/by-username/<var>/", methods: ["GET"], status: "ACTIVE", public: true, admin: false },
  { path: "api/users/check-availability/", methods: ["POST"], status: "ACTIVE", public: true, admin: false },
  { path: "api/users/contact/", methods: ["POST"], status: "ACTIVE", public: true, admin: false },
  { path: "api/users/data-export/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/users/me/verify/", methods: ["POST"], status: "ACTIVE", public: false, admin: false },
  { path: "api/users/privacy/", methods: ["GET", "PUT"], status: "ACTIVE", public: false, admin: false },
  { path: "api/users/profile/", methods: ["PUT", "PATCH"], status: "ACTIVE", public: false, admin: false },
  { path: "api/users/search/", methods: ["GET"], status: "ACTIVE", public: false, admin: false },
];

export const TOTAL_ROUTES = 143;

