# Generated by Django 5.2.7 on 2026-05-27 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_resource_type'),
        ('sphera', '0002_v2_fields_and_annale'),
    ]

    operations = [
        migrations.AddField(
            model_name='annalesession',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annalesession',
            name='qa_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='annalesession',
            name='resource',
            field=models.ForeignKey(blank=True, help_text='Ressource utilisée comme annale (si depuis une ressource existante)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annale_sessions', to='resources.resource'),
        ),
    ]
