# Generated by Django 5.2.7 on 2025-10-26 03:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="resources/")),
                ("file_size", models.IntegerField()),
                ("file_type", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cours", "Cours"),
                            ("notes", "Notes"),
                            ("resumes", "Résumés"),
                            ("exercises", "Exercices"),
                            ("projects", "Projets"),
                            ("presentations", "Présentations"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("university", "Université uniquement"),
                            ("friends", "Amis uniquement"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("audience", models.CharField(blank=True, max_length=200)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("impact_score", models.IntegerField(default=0)),
                ("downloads_count", models.IntegerField(default=0)),
                ("views_count", models.IntegerField(default=0)),
                ("saves_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResourceSave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-saved_at"],
            },
        ),
        migrations.CreateModel(
            name="ResourceView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-viewed_at"],
            },
        ),
    ]
