# Generated by Django 5.2.7 on 2026-05-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20260407_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_cards/'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
