# Generated by Django 5.2.7 on 2026-04-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0006_merge_20260407_2136"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone_number", ""), _negated=True),
                fields=("phone_number",),
                name="uniq_user_phone_number_non_empty",
            ),
        ),
    ]
