# Generated by Django 5.2.7 on 2026-05-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_mood',
            field=models.CharField(blank=True, default='excited', max_length=100),
        ),
    ]
