# Generated by Django 5.2.7 on 2026-05-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_current_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
