# Generated by Django 5.2.7 on 2026-05-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_tools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='tool_type',
        ),
        migrations.AddField(
            model_name='studysession',
            name='tool_types',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
